### ISSUE TITLE
现在还有渠道获取最新的代码么?

### ISSUE THREAD

**Issue by wenerme** [iccfish/12306_ticket_helper#3]
谢谢~

**Comment by iccfish** [comment]
暂时没有，这里的代码也比较老了，基本上只能供参考一下，因为老的12306已经被废弃了。新版本12306高峰期的卡顿是助手层面所无法解决的，所以这个已经很难再继续了。另外就是因为一些关系，所以面对新版本的助手并没有在GitHub开源（实际上是全新的），这也是因为考虑到就算开源也没有多大用处了。

**Comment by iccfish** [comment]
我的软件版12306订票助手.NET目前还没有开源，因为开源的风险太难以控制了 :-)
