### ISSUE TITLE
能否提交chrome商店？新版chrome不让使用不在商店里的插件。

### ISSUE THREAD

**Issue by leo-plus** [iccfish/12306_ticket_helper#5]

**Comment by iccfish** [comment]
很抱歉，这个仓库的代码实际上已经过时了（无法再使用了）。出于很多原因，我也无法提供能在chrome或Firefox上使用的最后版本代码。
然后就目前来说，我已经不维护适用于浏览器的订票软件了。如果可能的话，请关注我的软件版：[12306订票助手.NET](http://www.fishlee.net/soft/12306/)，以及[我的博客](https://blog.baidu.com/)
